Drivetrain, PID Heading Specifically
FRC125/NU17-FRamework pull request #18
Opened 2017-02-11 19:35 UTC by JYoung413

This is almost what we have right now but with a lot more of functionality, I added a pid controller called controlOutput which just combines different streams. I made some methods for changing setpoints, but right now pressing A on a xbox gamepad should hold a straight drive given the setpoint of 0.0.

2017-02-15 15:17 UTC, MiloDavis requested changes

2017-02-15 15:17 UTC, MiloDavis commented on .idea/modules.xml
> +</project>
Add newline at end of file

2017-02-15 15:17 UTC, MiloDavis commented on NU17-FRamework.iml
> +<?xml version="1.0" encoding="UTF-8"?>
Should this file be added?

2017-02-15 15:17 UTC, MiloDavis commented on src/com/nutrons/steamworks/ButtonTest.java
> +package com.nutrons.steamworks;
Do we still need this file?

2017-02-15 15:17 UTC, MiloDavis commented on src/com/nutrons/steamworks/Drivetrain.java
> +import com.nutrons.framework.controllers.*;
No wildcard imports

2017-02-15 15:17 UTC, MiloDavis commented on src/com/nutrons/steamworks/Drivetrain.java
> +   * A drivetrain which uses Arcade Drive. AKA Cheezy Drive
Remove AKA Cheezy Drive

2017-02-15 15:17 UTC, MiloDavis commented on src/com/nutrons/steamworks/Drivetrain.java
> +    this.throttle = throttle.map(deadbandMap(-deadband, deadband, 0.0)).subscribeOn(Schedulers.io()).onBackpressureDrop();
Remove onBackpressureDrop, this should be added by default

2017-02-15 15:17 UTC, MiloDavis commented on src/com/nutrons/steamworks/Drivetrain.java
> +    this.yaw = yaw.map(deadbandMap(-deadband, deadband, 0.0)).subscribeOn(Schedulers.io()).onBackpressureDrop();
Remove onBackpressureDrop, this should be added by default

2017-02-15 15:17 UTC, MiloDavis commented on src/com/nutrons/steamworks/Drivetrain.java
> +              System.out.println(x + " = Gyro Readings");
Cut this out.

2017-02-15 15:17 UTC, MiloDavis commented on src/com/nutrons/steamworks/Drivetrain.java
> +    //this.holdHeadingCmd = Command.create(() -> holdHeadingAction());
Cut this out

2017-02-15 15:17 UTC, MiloDavis commented on src/com/nutrons/steamworks/Drivetrain.java
> +            .onBackpressureDrop()
No longer needed

2017-02-15 15:17 UTC, MiloDavis commented on src/com/nutrons/steamworks/Drivetrain.java
> +            .onBackpressureDrop()
No longer needed

2017-02-15 15:17 UTC, MiloDavis commented on src/com/nutrons/steamworks/Drivetrain.java
> +            .onBackpressureDrop()
No longer needed

2017-02-15 15:17 UTC, MiloDavis commented on src/com/nutrons/steamworks/Drivetrain.java
> +              System.out.println(x);
Remove extra print

2017-02-15 15:17 UTC, MiloDavis commented on src/com/nutrons/steamworks/Drivetrain.java
> +            .onBackpressureDrop()
No longer needed

2017-02-15 15:17 UTC, MiloDavis commented on src/com/nutrons/steamworks/RobotBootstrapper.java
> +    //this.serial = new Serial(PACKET_LENGTH *2, PACKET_LENGTH);
Should this still be commented out?

2017-02-15 15:17 UTC, MiloDavis commented on src/com/nutrons/steamworks/RobotBootstrapper.java
>      this.driverPad = new WpiXboxGamepad(RobotMap.DRIVER_PAD);
This will need to be switched to CommonController

2017-02-15 15:17 UTC, MiloDavis commented on src/com/nutrons/steamworks/RobotBootstrapper.java
> +    sm.registerSubsystem(new Drivetrain(driverPad.joy2X().map(x -> -x), driverPad.joy1Y().map(x -> x), this.driverPad.button(1),
Remove identity map

2017-02-15 16:36 UTC, totallyashes commented on NU17-FRamework.iml
> +<?xml version="1.0" encoding="UTF-8"?>
If this is in the .idea folder, sure. If this is a new file, get rid of it.

2017-02-15 16:37 UTC, totallyashes commented on src/com/nutrons/steamworks/RobotBootstrapper.java
> +    //this.serial = new Serial(PACKET_LENGTH *2, PACKET_LENGTH);
Once lydia fixes the exception on serial not found, we won't have to comment this out to run our tests.

2017-02-16 18:18 UTC, totallyashes commented
I'm going to close this. Check #21.

2017-02-16 18:18 UTC, closed without merging